import type { Metadata } from "next";
import { LegalPage } from "../components/public-shell";

export const metadata: Metadata = { title: "Privacy Policy | Excela", description: "How Excela handles your account, announcements, and Google Sheets access." };

export default function Privacy() {
  return <LegalPage title="Privacy policy." intro="Your planner belongs to you. Here’s what Excela processes to help you keep it up to date.">
    <section><h2>01 / Information we use</h2><p>When you sign in with Google, Excela receives your Google account identifier, name, email address, and profile picture, if available. We store your account details, chosen planner link and identifiers, account timestamps, and encrypted Google authorization credentials and your encrypted Ollama API key in our database.</p><p>We also store session records, including expiration times and browser information, to keep you signed in. A necessary, HttpOnly cookie identifies your session.</p></section>
    <section><h2>02 / Your announcements and AI</h2><p>During setup you provide your own Ollama API key. Excela uses it on the server to authenticate your AI requests to Ollama, using your account allowance. You can replace it in Setup; deleting your Excela account removes the stored key. You can revoke the key separately in your Ollama account.</p><p>When you submit an announcement, its text is sent to Ollama’s cloud service, which extracts courses, event titles, and dates. Only paste information you have permission to share; avoid sensitive or unnecessary personal information.</p><p>The current application does not save announcement text or generated event history to its account database. Generated entries are saved in your Google Sheet when you inject them. Ollama processes submitted text under its own terms and privacy practices; this policy does not promise a particular retention period on its behalf.</p></section>
    <section><h2>03 / Google Sheets access</h2><p>Excela uses your permission to check the planner you connect, read its month tabs and calendar cells, and write extracted events. Excela requests Google’s drive.file permission for files you create with Excela or explicitly choose through Google’s file chooser. If you choose Generate template, it imports the public planner template into a new Google Sheet in your account.</p><p>Writing events does not require another AI call. The sync workflow does not send your existing spreadsheet contents or Google authorization tokens to an AI provider.</p><p>Excela’s use of information received from Google APIs follows the <a href="https://developers.google.com/terms/api-services-user-data-policy">Google API Services User Data Policy</a>, including its Limited Use requirements. Google user data is used to provide these user-facing features, not for advertising or training general-purpose AI models.</p></section>
    <section><h2>04 / Storage and service providers</h2><p>Account and session information is stored in MongoDB. Google handles authentication and spreadsheet storage, while Ollama processes submitted announcements. Hosting and database services process data needed to operate the application. Operational logs may contain technical error details. We do not sell your personal information.</p><p>Google refresh tokens and Ollama API keys are encrypted before storage, and session cookies are not accessible to page JavaScript. When you open Google’s file chooser, a short-lived access token is used in browser memory to display it; refresh tokens and client secrets stay on the server. No online service can guarantee absolute security.</p></section>
    <section><h2>05 / Retention and your choices</h2><p>Account information is retained while your account exists. Sessions expire and are periodically removed. You can change your linked planner, sign out, or use Delete account in the app’s account menu.</p><p>Deleting your account removes your account and session records from the application database and attempts to revoke Google access. It does not delete spreadsheets in your Google account or data retained independently by Ollama. You can also remove Excela’s access through your <a href="https://myaccount.google.com/connections">Google Account connections</a>.</p></section>
    <section><h2>06 / Changes and questions</h2><p>We may update this policy as the application changes. The date above identifies the latest version. For privacy questions or requests about your data, contact <a href="mailto:shifatsrm09@gmail.com">shifatsrm09@gmail.com</a>.</p></section>
  </LegalPage>;
}
