import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "../components/public-shell";

export const metadata: Metadata = { title: "Terms of Service | Excela", description: "Terms for using Excela and its Google Sheets planner integration." };

export default function Terms() {
  return <LegalPage title="Terms of service." intro="A few ground rules for using Excela to organize your academic schedule.">
    <section><h2>01 / Using Excela</h2><p>These terms govern your use of Excela. By using the service, you agree to these terms. If you do not agree, do not use it. You must be permitted to use your Google account and authorize access to any spreadsheet you connect.</p><p>Excela extracts academic events from text with Ollama’s AI service and adds them to a Google Sheets planner. Features may change as the application develops.</p></section>
    <section><h2>02 / Your account and permissions</h2><p>You are responsible for keeping your Google account secure and for choosing the correct planner. Only submit content and connect sheets you have permission to use. When you choose Inject, you authorize Excela to process that announcement with Ollama and write the extracted events to your connected planner.</p><p>Generating a template authorizes creation of a planner in your Google account. You retain ownership of your content and spreadsheets; you permit the processing needed to carry out the actions you request.</p></section>
    <section><h2>03 / Check the results</h2><p>AI can misunderstand announcements, omit events, or extract incorrect dates. Check the entries in your planner against the original announcement. Excela is an organizational aid, not an authoritative source of class schedules or a guarantee that you will meet a deadline.</p><p>Writes may fail or be affected by concurrent edits, provider limits, connectivity, or revoked permissions. Keep a copy of important information and check sync results.</p></section>
    <section><h2>04 / Acceptable use</h2><p>Do not use Excela for unlawful activity, unauthorized access, or processing content you are not entitled to share. Do not attempt to bypass security controls, access another user’s data, or disrupt the service. Access may be restricted where necessary to address misuse or security issues.</p></section>
    <section><h2>05 / Third-party services and privacy</h2><p>Excela depends on Google, Ollama, and hosting and database services. Their availability, account requirements, and applicable terms also affect your use. See our <Link href="/privacy">Privacy Policy</Link> for how data is processed and how to disconnect access.</p></section>
    <section><h2>06 / Availability and responsibility</h2><p>Excela is provided as available, without a promise of uninterrupted operation or error-free output. To the extent permitted by applicable law, we disclaim implied warranties and liability for indirect losses arising from use of the service. Nothing in these terms excludes rights or liabilities that applicable law does not allow to be excluded.</p></section>
    <section><h2>07 / Leaving and changes</h2><p>You may stop using Excela, revoke Google access, or delete your account at any time. Account deletion removes the app’s stored account and session records; your Google spreadsheets remain in your Google account.</p><p>These terms may be updated as the service changes. The latest version will be posted here with its update date. For questions, contact <a href="mailto:shifatsrm09@gmail.com">shifatsrm09@gmail.com</a>.</p></section>
  </LegalPage>;
}
